In [1]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
from scipy import linalg, optimize

In [3]:
np.info(optimize.fmin)

 fmin(func, x0, args=(), xtol=0.0001, ftol=0.0001, maxiter=None, maxfun=None,
      full_output=0, disp=1, retall=0, callback=None)

Minimize a function using the downhill simplex algorithm.

This algorithm only uses function values, not derivatives or second
derivatives.

Parameters
----------
func : callable func(x,*args)
    The objective function to be minimized.
x0 : ndarray
    Initial guess.
args : tuple, optional
    Extra arguments passed to func, i.e. ``f(x,*args)``.
callback : callable, optional
    Called after each iteration, as callback(xk), where xk is the
    current parameter vector.
xtol : float, optional
    Relative error in xopt acceptable for convergence.
ftol : number, optional
    Relative error in func(xopt) acceptable for convergence.
maxiter : int, optional
    Maximum number of iterations to perform.
maxfun : number, optional
    Maximum number of function evaluations to make.
full_output : bool, optional
    Set to True if fopt and warnflag outputs are desi

In [4]:
a = np.r_[3, [0]*5, -1:1:10j]

In [5]:
a

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [6]:
np.mgrid[0:5, 0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [7]:
np.mgrid[0:5:5j, 0:5:4j]

array([[[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.25      ,  1.25      ,  1.25      ,  1.25      ],
        [ 2.5       ,  2.5       ,  2.5       ,  2.5       ],
        [ 3.75      ,  3.75      ,  3.75      ,  3.75      ],
        [ 5.        ,  5.        ,  5.        ,  5.        ]],

       [[ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ]]])

In [9]:
from numpy import poly1d

In [11]:
p = poly1d([1,2, 3])

In [12]:
p

poly1d([1, 2, 3])

In [15]:
p *p

poly1d([ 1,  4, 10, 12,  9])

In [16]:
p.integ(k=6)

poly1d([ 0.33333333,  1.        ,  3.        ,  6.        ])

In [17]:
p.deriv()

poly1d([2, 2])

In [18]:
p([4, 5])

array([27, 38])

In [20]:
def addsubtract(a, b):
    if a > b:
        return a - b
    else:
        return b - a

In [22]:
vec_addsubtract = np.vectorize(addsubtract)

In [23]:
vec_addsubtract([0, 2, 3, 8], [6, 1, 4, 8])

array([6, 1, 1, 0])

In [24]:
np.cast['f'](np.pi)

array(3.1415927410125732, dtype=float32)

In [25]:
x = np.r_[-2:3]

In [26]:
x

array([-2, -1,  0,  1,  2])

In [27]:
np.select([x > 3, x >= 0], [0, x+2])

array([0, 0, 2, 3, 4])