In [1]:
import numpy as np

arange

In [3]:
np.arange(3)

array([0, 1, 2])

In [4]:
np.arange(3.0)

array([ 0.,  1.,  2.])

In [5]:
np.arange(2, 5)

array([2, 3, 4])

In [6]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

array

In [7]:
np.array([1, 2, 3])

array([1, 2, 3])

In [8]:
np.array([1, 2, 3.0])

array([ 1.,  2.,  3.])

In [9]:
np.array([[1, 2], [2, 3]])

array([[1, 2],
       [2, 3]])

In [11]:
np.array([1, 2, 3], dtype=complex)

array([ 1.+0.j,  2.+0.j,  3.+0.j])

In [12]:
 x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])

In [13]:
x['a']

array([1, 3])

In [15]:
np.array(np.matrix('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [17]:
np.array(np.matrix('1 2;3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

copy

In [18]:
x = np.array(np.arange(3))

In [19]:
z = np.copy(x)

In [20]:
z

array([0, 1, 2])

empty

In [21]:
np.empty((2, 3))

array([[ 1.,  0.,  2.],
       [ 0.,  3.,  0.]])

In [22]:
np.empty((2, 3), dtype=int)

array([[         0, 1072693248,          0],
       [1073741824,          0, 1074266112]])

empty_like

In [23]:
y = np.empty_like(x) #Same Shape and Type like x

In [24]:
y

array([1072693248, 1073741824, 1074266112])

eye

In [25]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [29]:
np.eye(3, k=1)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

fromfile

In [30]:
dt = np.dtype([('time', [('min', int), ('sec', int)]),
...                ('temp', float)])

In [31]:
x = np.zeros((1,), dtype=dt)

In [32]:
x['time']['min'] = 10; x['temp'] = 98.25

In [33]:
x

array([((10, 0), 98.25)], 
      dtype=[('time', [('min', '<i4'), ('sec', '<i4')]), ('temp', '<f8')])

formfunction

In [37]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]], dtype=bool)

In [38]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

identity

In [41]:
np.identity((3))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

linspace

In [42]:
np.linspace(2, 10, 4)

array([  2.        ,   4.66666667,   7.33333333,  10.        ])

In [43]:
np.linspace(2, 5, 5, endpoint=False)

array([ 2. ,  2.6,  3.2,  3.8,  4.4])

In [44]:
np.linspace(2.0, 3.0, 5, retstep=True)

(array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)

In [45]:
import matplotlib.pyplot as plt

In [46]:
N=8

In [47]:
y = np.zeros(N)

In [48]:
x1 = np.linspace(0, 10, N, endpoint=True)

In [49]:
x2 = np.linspace(0, 10, N, endpoint=False)

In [50]:
plt.plot(x1, y, 'o')

In [51]:
plt.plot(x2, y+0.5, 'o')

In [52]:
plt.ylim([-0.5, 1])

(-0.5, 1)

In [53]:
plt.show()

logspace

In [54]:
np.logspace(2, 3, num=4)

array([  100.        ,   215.443469  ,   464.15888336,  1000.        ])

In [56]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519])

In [57]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        ])

In [62]:
N=8

In [63]:
x1=np.logspace(0.1, 1, N, endpoint=True)

In [64]:
x2=np.logspace(0.1, 1, N, endpoint=False)

In [65]:
plt.plot(x1, y, 'o')

In [66]:
plt.plot(x2, y + 0.5, 'o')

In [67]:
plt.ylim([-0.5, 1])

(-0.5, 1)

In [68]:
plt.show()

mgrid

In [70]:
np.mgrid[0:5, 0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [71]:
np.mgrid[-1:1:5j]

array([-1. , -0.5,  0. ,  0.5,  1. ])

ogrid

In [72]:
from numpy import ogrid

In [74]:
ogrid[-1:1:5j]

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [76]:
ogrid[0:5,0:5]

[array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[0, 1, 2, 3, 4]])]

ones

In [77]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [78]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [79]:
np.ones((2, 1))

array([[ 1.],
       [ 1.]])

In [80]:
s = (2, 3)

In [81]:
np.ones(s)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

ones_like

In [82]:
np.ones_like(np.ones(3))

array([ 1.,  1.,  1.])

In [83]:
x = np.ones(3, dtype=float)

In [84]:
np.ones_like(x)

array([ 1.,  1.,  1.])

zeros

In [85]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [86]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [87]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) #Custom Datatype

array([(0, 0), (0, 0)], 
      dtype=[('x', '<i4'), ('y', '<i4')])

zeros_like

In [88]:
np.zeros_like(np.zeros((3, 4), dtype=float))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])