In [4]:
import numpy as np

cross

In [5]:
x = [1, 2, 3]

In [6]:
y = [2, 3, 4]

In [7]:
np.cross(x, y)

array([-1,  2, -1])

dot

In [8]:
a = np.array([[1, 2], [3, 4]])

In [10]:
b = np.array([[5, 6], [7, 8]])

In [11]:
np.cross(a, b)

array([-4, -4])

outer

In [12]:
r1 = np.outer(np.ones((5,)), np.linspace(-2, 2, 5))

In [13]:
r1

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [14]:
x = np.array(['a','b','c'], dtype=object)

In [15]:
np.outer(x, [1, 2, 3])

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

linalg.svd

In [16]:
a = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)
b = np.random.randn(2, 7, 8, 3) + 1j*np.random.randn(2, 7, 8, 3)

In [17]:
u, s, vh = np.linalg.svd(a, full_matrices=True)

In [19]:
u.shape, s.shape, vh.shape

((9, 9), (6,), (6, 6))

vdot

In [20]:
a = np.array([1+2j, 2+2j])

In [21]:
b = np.array([2+3j, 2+2j])

In [22]:
np.vdot(a, b)

(16-1j)