In [2]:
import numpy as np

ndarray.astype

In [3]:
x= np.array([1,2,3])

In [4]:
x.astype(int)

array([1, 2, 3])

atleast_1d

In [5]:
np.atleast_1d([1])

array([1])

In [6]:
x = np.arange(9.0).reshape(3, 3)

In [7]:
np.atleast_1d(x)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [8]:
np.atleast_1d(x) is x

True

atleast_2d

In [9]:
np.atleast_2d([1])

array([[1]])

In [10]:
np.atleast_2d([1, 2])

array([[1, 2]])

In [11]:
np.atleast_2d(np.arange(3.0))

array([[ 0.,  1.,  2.]])

atleast_3d

In [12]:
np.atleast_3d([3])

array([[[3]]])

In [13]:
x = np.arange(12).reshape(3, 4)

In [15]:
np.atleast_3d(x).shape

(3, 4, 1)

mat

In [16]:
x = np.array([[1, 2],[3, 4]])

In [20]:
m = np.asmatrix(x)

In [21]:
m

matrix([[1, 2],
        [3, 4]])