In [1]:
import numpy as np

In [2]:
a = np.arange(12)**2

In [3]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [4]:
i = np.array([1, 3, 4, 6, 7])

In [5]:
a[i]

array([ 1,  9, 16, 36, 49])

In [6]:
j = np.array([[1, 2],[5, 6]])

In [7]:
a[j]

array([[ 1,  4],
       [25, 36]])

In [8]:
palette = np.array( [ [0,0,0],                # black
...                       [255,0,0],              # red
...                       [0,255,0],              # green
...                       [0,0,255],              # blue
...                       [255,255,255] ] ) 

In [9]:
image = np.array( [ [ 0, 1, 2, 0 ],           # each value corresponds to a color in the palette
...                     [ 0, 3, 4, 0 ]  ] )

In [10]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [11]:
a = np.arange(12).reshape(3, 4)

In [12]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
i = np.array([[0, 1],
                 [1, 2]])

In [18]:
j = np.array([[2, 1],
             [3, 3]])

In [19]:
a[i]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [21]:
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [22]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [23]:
l = [i, j]

In [24]:
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [25]:
s = np.array([i, j])

In [26]:
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [27]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [28]:
time = np.linspace(20, 145, 5)

In [29]:
data = np.sin(np.arange(20)).reshape(5, 4)

In [30]:
time

array([  20.  ,   51.25,   82.5 ,  113.75,  145.  ])

In [31]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [33]:
ind = data.argmax(axis=0)

In [34]:
ind

array([2, 0, 3, 1], dtype=int64)

In [37]:
time_max = time[ind]

In [38]:
time_max

array([  82.5 ,   20.  ,  113.75,   51.25])

In [39]:
data.shape

(5, 4)

In [40]:
type(data.shape)

tuple

In [43]:
data.shape[0]

5

In [44]:
data_max = data[ind, range(data.shape[1])]

In [45]:
data_max

array([ 0.98935825,  0.84147098,  0.99060736,  0.6569866 ])

In [48]:
a = np.array([1, 2, 3, 4, 5, 6])

In [49]:
a

array([1, 2, 3, 4, 5, 6])

In [51]:
a[[1, 2, 3]] = 0

In [52]:
a

array([1, 0, 0, 0, 5, 6])

In [53]:
a[[1, 2, 3]] += 10

In [54]:
a

array([ 1, 10, 10, 10,  5,  6])

In [55]:
a = np.arange(12).reshape(3, 4)

In [56]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
b  = a > 5

In [58]:
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [59]:
a[b]

array([ 6,  7,  8,  9, 10, 11])

In [60]:
a[b] = 0

In [61]:
a

array([[0, 1, 2, 3],
       [4, 5, 0, 0],
       [0, 0, 0, 0]])

In [63]:
a.shape

(3, 4)

In [64]:
b1 = np.array([True, False, True])

In [65]:
b2 = np.array([True, True, False, False])

In [66]:
a[b1, :]

array([[0, 1, 2, 3],
       [0, 0, 0, 0]])

In [67]:
a[b1]

array([[0, 1, 2, 3],
       [0, 0, 0, 0]])

In [68]:
a[:, b2]

array([[0, 1],
       [4, 5],
       [0, 0]])

In [69]:
a[b1, b2]

array([0, 0])

In [70]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])

In [71]:
ax, bx, cx = np.ix_(a, b, c)

In [72]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [74]:
bx

array([[[8],
        [5],
        [4]]])

In [75]:
cx

array([[[5, 4, 6, 8, 3]]])

In [76]:
ax.shape, bx.shape, cx.shape

((4, 1, 1), (1, 3, 1), (1, 1, 5))

In [78]:
results = ax+bx+cx

In [79]:
results[3, 2, 4]

12

In [80]:
a[3]+b[2]*c[4]

17

In [91]:
a = np.array([[1, 2], [4, 5]])

In [82]:
a.transpose()

array([[1, 4],
       [2, 5]])

In [83]:
np.linalg.inv(a)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [84]:
u = np.eye(2)

In [85]:
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [86]:
j = np.array([[0.0, 1.0], [-1.0, 0.0]])

In [87]:
np.dot(j, j)

array([[-1.,  0.],
       [ 0., -1.]])

In [88]:
np.trace(u)

2.0

In [93]:
np.linalg.eig(j)

(array([ 0.+1.j,  0.-1.j]),
 array([[ 0.70710678+0.j        ,  0.70710678-0.j        ],
        [ 0.00000000+0.70710678j,  0.00000000-0.70710678j]]))

In [94]:
a= np.arange(30)

In [95]:
a.shape = 2, -1, 3

In [96]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [97]:
import matplotlib.pyplot as plt

In [98]:
mu, sigma = 2, 0.5

In [99]:
v = np.random.normal(mu, sigma, 10000)

In [100]:
plt.hist(v, bins=50, normed=1)

(array([ 0.00124559,  0.        ,  0.        ,  0.        ,  0.00249118,
         0.00249118,  0.00747354,  0.01494709,  0.01743827,  0.02117504,
         0.0411045 ,  0.08220899,  0.10213844,  0.11210317,  0.14573412,
         0.20054012,  0.28524029,  0.34129187,  0.43097441,  0.4857804 ,
         0.57172617,  0.64023366,  0.68382934,  0.75981037,  0.78721337,
         0.80465164,  0.76479274,  0.78223101,  0.68756611,  0.6751102 ,
         0.57297176,  0.56176144,  0.44343032,  0.33880069,  0.27527556,
         0.20925925,  0.17687389,  0.13701499,  0.09715608,  0.06352513,
         0.05231481,  0.02366622,  0.03238536,  0.00996473,  0.00249118,
         0.00373677,  0.        ,  0.00124559,  0.        ,  0.00249118]),
 array([-0.05704548,  0.02323771,  0.1035209 ,  0.18380409,  0.26408728,
         0.34437047,  0.42465366,  0.50493685,  0.58522003,  0.66550322,
         0.74578641,  0.8260696 ,  0.90635279,  0.98663598,  1.06691917,
         1.14720236,  1.22748555,  1.30776874,  1

In [101]:
plt.show()

In [102]:
(n, bins) = np.histogram(v, bins=50, normed =True)

In [103]:
plt.plot(.5*(bins[1:]+bins[:-1]), n)

In [104]:
plt.show()