In [2]:
import numpy as np

array_split

In [3]:
x = np.arange(3.0)

In [4]:
np.array_split(x, 3)

[array([ 0.]), array([ 1.]), array([ 2.])]

column_stack

In [5]:
a = np.array([1, 2, 3])

In [6]:
b = np.array([4, 5, 6])

In [7]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

concatenate

In [8]:
a = np.array([[2, 3], [4, 5]])

In [11]:
b = np.array([[1, 2]])

In [12]:
np.concatenate((a, b), axis = 0)

array([[2, 3],
       [4, 5],
       [1, 2]])

In [14]:
np.concatenate((a, b.T), axis=1)

array([[2, 3, 1],
       [4, 5, 2]])

In [15]:
np.ma.arange(3)

masked_array(data = [0 1 2],
             mask = False,
       fill_value = 999999)

diagonal

In [22]:
a= np.arange(9).reshape(3, 3)

In [23]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
a.diagonal(0)

array([0, 4, 8])

In [26]:
a.diagonal(1)

array([1, 5])

In [27]:
a.diagonal(2)

array([2])

In [28]:
a = np.arange(8).reshape(2, 2, 2)

In [29]:
a.diagonal(0, 0, 1)

array([[0, 6],
       [1, 7]])

dsplit

In [31]:
x= np.arange(16).reshape(2, 2, 4)

In [32]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [33]:
np.dsplit(x, 2)

[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]), array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]

dstack

In [34]:
a = np.array([1, 2, 3])

In [35]:
b=  np.array([4, 5, 6])

In [36]:
np.dstack((a, b))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [37]:
a = np.array([[1],[2],[3]])

In [40]:
b = np.array([[4],[5], [6]])

In [41]:
np.dstack((a, b))

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

hsplit

In [42]:
x = np.arange(16).reshape(4, 4)

In [43]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
np.hsplit(x, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [46]:
x = np.arange(8.0).reshape(2, 2, 2)

In [48]:
np.hsplit(x, 2)

[array([[[ 0.,  1.]],
 
        [[ 4.,  5.]]]), array([[[ 2.,  3.]],
 
        [[ 6.,  7.]]])]

hstack

In [49]:
a = np.array([1, 2,3 ])

In [50]:
b = np.array([2, 3, 4])

In [51]:
np.hstack((a, b))

array([1, 2, 3, 2, 3, 4])

In [53]:
a = np.array([[1],[2],[3]])

In [54]:
b = np.array([[2],[3],[4]])

In [55]:
np.hstack((a, b))

array([[1, 2],
       [2, 3],
       [3, 4]])

ndarray.item

In [57]:
x = np.random.randint(9, size=(3, 3))

In [59]:
x.item(3)

6

In [60]:
x

array([[5, 1, 7],
       [6, 2, 6],
       [5, 5, 3]])

newaxis

In [61]:
x = np.array([1,2 , 3])

In [63]:
from numpy import newaxis
x[:,newaxis]

array([[1],
       [2],
       [3]])

ravel

In [64]:
x = np.array([[1, 2, 3],[2, 3, 4]])

In [65]:
print(np.ravel(x))

[1 2 3 2 3 4]


In [66]:
np.ravel(x, order='A')

array([1, 2, 3, 2, 3, 4])

In [67]:
np.ravel(x.T)

array([1, 2, 2, 3, 3, 4])

In [68]:
np.ravel(x.T, order='K')

array([1, 2, 3, 2, 3, 4])

In [69]:
np.arange(12).reshape(2, 3, 2).swapaxes(1, 2)

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

repeat

In [70]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [71]:
x = np.array([[1,2 ], [3, 4]])

In [72]:
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [73]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [74]:
np.repeat(x, [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

reshape

In [75]:
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

resize

In [76]:
a = np.array([[1, 2], [3, 4]])

In [77]:
a.resize(2, 3)

In [78]:
a

array([[1, 2, 3],
       [4, 0, 0]])

In [80]:
np.resize(a, (1, 4))

array([[1, 2, 3, 4]])

In [81]:
np.resize(a, (2, 4))

array([[1, 2, 3, 4],
       [0, 0, 1, 2]])

sqeeze

In [82]:
x = np.array([[[0], [1], [2]]])

In [83]:
x.shape

(1, 3, 1)

In [84]:
np.squeeze(x).shape

(3,)

In [89]:
np.squeeze(x, axis = 0).shape

(3, 1)

In [90]:
np.squeeze(x, axis = 2).shape

(1, 3)

swapaxes

In [93]:
x = np.array([[1, 2, 3]])

In [94]:
np.swapaxes(x, 0, 1)

array([[1],
       [2],
       [3]])

In [96]:
x = np.array([[[1, 2],[2, 3], [3, 4]]])

In [97]:
np.swapaxes(x, 0, 2)

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]]])

take

In [98]:
a = [1, 2, 3, 4,5 , 6]

In [99]:
np.take(a, [0, 2, 4])

array([1, 3, 5])

In [100]:
np.take(a, [[0, 1], [2, 3]])

array([[1, 2],
       [3, 4]])

transport

In [101]:
x = np.arange(12).reshape(3, 4)

In [103]:
np.transpose(x)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [105]:
x = np.ones((1, 2, 3))


In [106]:
np.transpose(x, (1, 0, 2)).shape

(2, 1, 3)

vsplit

In [107]:
x = np.arange(16).reshape(4, 4)

In [108]:
np.vsplit(x, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [109]:
np.vsplit(x, np.array([3,6]))

C:\Users\Rittick\Anaconda3\lib\site-packages\numpy\lib\shape_base.py:431: FutureWarning: in the future np.array_split will retain the shape of arrays with a zero size, instead of replacing them by `array([])`, which always has a shape of (0,).
  FutureWarning)


[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]]), array([], dtype=int32)]

vstack

In [110]:
a = np.array([1, 2,3 ])

In [111]:
b = np.array([2, 3, 4])

In [112]:
np.vstack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [113]:
a = np.array([[1],[2],[3]])

In [114]:
b = np.array([[2],[3],[4]])

In [115]:
np.vstack((a, b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])