In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [7]:
a.itemsize

4

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b  = np.array([1, 2, 3])

In [11]:
b

array([1, 2, 3])

In [12]:
type(b)

numpy.ndarray

In [13]:
b = np.array([(1, 2), (3, 4)])

In [14]:
b

array([[1, 2],
       [3, 4]])

In [15]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [16]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
np.empty((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [18]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [19]:
np.arange(0, 1, 0.5)

array([ 0. ,  0.5])

In [20]:
from numpy import pi
np.linspace(0, 2, 9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [21]:
x = np.linspace(0, 2 * pi, 100)

In [22]:
x

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [23]:
f = np.sin(x)

In [24]:
f

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

In [25]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [26]:
b = np.arange(10).reshape(2, 5)

In [27]:
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [28]:
c = np.arange(24).reshape(2, 3, 4)

In [29]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [30]:
print(np.arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [32]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [33]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)

In [34]:
a- b

array([10, 19, 28, 37])

In [35]:
b ** 2

array([0, 1, 4, 9])

In [36]:
10 * np.sin(a)

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [37]:
a < 2

array([False, False, False, False], dtype=bool)

In [38]:
a<20

array([ True, False, False, False], dtype=bool)

In [39]:
A = np.array([[1, 2], 
             [3, 4]])

In [40]:
B = np.array([[5, 6],
             [7, 8]])

In [41]:
A*B

array([[ 5, 12],
       [21, 32]])

In [42]:
A.dot(B)

array([[19, 22],
       [43, 50]])

In [43]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [44]:
a = np.ones((2, 3), dtype=int)
b = np.random.random((2, 3))

In [45]:
a*=3

In [46]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [47]:
b

array([[ 0.69490631,  0.08172384,  0.76000076],
       [ 0.32760943,  0.62304628,  0.77187328]])

In [48]:
a + b

array([[ 3.69490631,  3.08172384,  3.76000076],
       [ 3.32760943,  3.62304628,  3.77187328]])

In [49]:
b += a

In [50]:
b

array([[ 3.69490631,  3.08172384,  3.76000076],
       [ 3.32760943,  3.62304628,  3.77187328]])

In [51]:
a+=b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [52]:
a  = np.random.random((2, 3))

In [53]:
a

array([[ 0.15219199,  0.15142633,  0.42702808],
       [ 0.97400839,  0.36365359,  0.57261377]])

In [54]:
a.sum()

2.6409221596465375

In [55]:
a.min()

0.1514263341439348

In [56]:
a.max()

0.97400839392018479

In [57]:
b=  np.arange(15).reshape(3, 5)

In [58]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
b.sum(axis=0)

array([15, 18, 21, 24, 27])

In [60]:
b.sum(axis=1)

array([10, 35, 60])

In [61]:
b.min(axis=0)

array([0, 1, 2, 3, 4])

In [62]:
b.min(axis=1)

array([ 0,  5, 10])

In [63]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13],
       [15, 18, 21, 24, 27]], dtype=int32)

In [64]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [66]:
B = np.arange(3)

In [67]:
B

array([0, 1, 2])

In [68]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [70]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [71]:
C = np.array([2, 3, 4])

In [72]:
np.add(B, C)

array([2, 4, 6])

In [73]:
a = np.arange(10) ** 3

In [74]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [75]:
a[:]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [76]:
a[:3]

array([0, 1, 8], dtype=int32)

In [77]:
a[3:]

array([ 27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [78]:
a[:5:2] = -1

In [79]:
a

array([ -1,   1,  -1,  27,  -1, 125, 216, 343, 512, 729], dtype=int32)

In [81]:
for i in a:
    print(i ** (1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


C:\Users\Rittick\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: invalid value encountered in power
  from ipykernel import kernelapp as app


In [84]:
def f(x, y):
    return 10*x+y

In [85]:
b = np.fromfunction(f, (5, 4), dtype=int)

In [86]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [87]:
b[2,3]

23

In [88]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [89]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [90]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [91]:
b[-1]

array([40, 41, 42, 43])

In [92]:
b[1]

array([10, 11, 12, 13])

In [95]:
c = np.array([
        [[1, 2, 3],
        [4, 5, 6]],
        [[7, 8, 9],
        [10, 11, 12]]
    ])



In [96]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [98]:
for row in b :
    print (row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [99]:
for elem in b.flat:
    print(elem)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [102]:
a = np.floor(10*np.random.random((3, 4)))

In [103]:
a

array([[ 2.,  0.,  7.,  7.],
       [ 4.,  6.,  5.,  5.],
       [ 9.,  7.,  5.,  6.]])

In [104]:
a.shape

(3, 4)

In [105]:
a.ravel()

array([ 2.,  0.,  7.,  7.,  4.,  6.,  5.,  5.,  9.,  7.,  5.,  6.])

In [106]:
a.reshape((4, 3))

array([[ 2.,  0.,  7.],
       [ 7.,  4.,  6.],
       [ 5.,  5.,  9.],
       [ 7.,  5.,  6.]])

In [107]:
a.T

array([[ 2.,  4.,  9.],
       [ 0.,  6.,  7.],
       [ 7.,  5.,  5.],
       [ 7.,  5.,  6.]])

In [108]:
a.T.shape

(4, 3)

In [109]:
a.T.shape

(4, 3)

In [110]:
a.T

array([[ 2.,  4.,  9.],
       [ 0.,  6.,  7.],
       [ 7.,  5.,  5.],
       [ 7.,  5.,  6.]])

In [111]:
a

array([[ 2.,  0.,  7.,  7.],
       [ 4.,  6.,  5.,  5.],
       [ 9.,  7.,  5.,  6.]])

In [112]:
a.resize((2, 6))

In [113]:
a

array([[ 2.,  0.,  7.,  7.,  4.,  6.],
       [ 5.,  5.,  9.,  7.,  5.,  6.]])

In [114]:
a = np.floor(10*np.random.random((2, 3)))

In [115]:
b = np.floor(10*np.random.random((2, 3)))

In [116]:
a

array([[ 1.,  5.,  1.],
       [ 7.,  1.,  9.]])

In [117]:
b

array([[ 3.,  1.,  0.],
       [ 2.,  0.,  5.]])

In [119]:
np.vstack((a, b))

array([[ 1.,  5.,  1.],
       [ 7.,  1.,  9.],
       [ 3.,  1.,  0.],
       [ 2.,  0.,  5.]])

In [120]:
np.hstack((a, b))

array([[ 1.,  5.,  1.,  3.,  1.,  0.],
       [ 7.,  1.,  9.,  2.,  0.,  5.]])

In [121]:
from numpy import newaxis

In [122]:
np.column_stack((a, b))

array([[ 1.,  5.,  1.,  3.,  1.,  0.],
       [ 7.,  1.,  9.,  2.,  0.,  5.]])

In [123]:
a = np.array([1,2 ])
b = np.array([3, 4])

In [124]:
np.column_stack((a, b))

array([[1, 3],
       [2, 4]])

In [125]:
np.hstack((a, b))

array([1, 2, 3, 4])

In [126]:
a[:, newaxis]

array([[1],
       [2]])

In [129]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[1, 3],
       [2, 4]])

In [130]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[1, 3],
       [2, 4]])

In [131]:
np.r_[1:4, 4, 5]

array([1, 2, 3, 4, 5])

In [136]:
a = np.floor(10*np.random.random((2,12)))

In [137]:
a

array([[ 8.,  4.,  5.,  9.,  3.,  1.,  1.,  8.,  2.,  6.,  9.,  8.],
       [ 8.,  3.,  6.,  2.,  0.,  8.,  1.,  7.,  8.,  1.,  6.,  5.]])

In [138]:
np.hsplit(a, 3)

[array([[ 8.,  4.,  5.,  9.],
        [ 8.,  3.,  6.,  2.]]), array([[ 3.,  1.,  1.,  8.],
        [ 0.,  8.,  1.,  7.]]), array([[ 2.,  6.,  9.,  8.],
        [ 8.,  1.,  6.,  5.]])]

In [139]:
np.hsplit(a, (3, 4))

[array([[ 8.,  4.,  5.],
        [ 8.,  3.,  6.]]), array([[ 9.],
        [ 2.]]), array([[ 3.,  1.,  1.,  8.,  2.,  6.,  9.,  8.],
        [ 0.,  8.,  1.,  7.,  8.,  1.,  6.,  5.]])]

In [146]:
a = np.arange(12)

In [147]:
b = a


In [148]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [149]:
b is a

True

In [151]:
b.shape = 4, 3

In [152]:
a.shape

(4, 3)

In [153]:
def f(x):
    print(id(x))

In [154]:
f(a)

89235248


In [155]:
c = a.view()

In [156]:
c is a

False

In [157]:
c.base is a

True

In [158]:
c.flags.owndata

False

In [159]:
c.shape

(4, 3)

In [160]:
a.shape

(4, 3)

In [164]:
c[2,2] = 123

In [165]:
c

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7, 123],
       [  9,  10,  11]])

In [166]:
s=a[: , 2:3]

In [167]:
s

array([[  2],
       [  5],
       [123],
       [ 11]])

In [168]:
d = a.copy()

In [169]:
d

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7, 123],
       [  9,  10,  11]])

In [170]:
d.size


12

In [171]:
d.shape

(4, 3)

In [172]:
d is a

False

In [173]:
d.base is a

False