In [1]:
import numpy as np

choose

In [2]:
choices = [[0, 1, 2, 3], [10, 11, 12, 13],
...   [20, 21, 22, 23], [30, 31, 32, 33]]

In [3]:
np.choose([2, 3, 1, 0], choices)

array([20, 31, 12,  3])

compress

In [4]:
a = np.array([[2, 3], [4, 5], [6, 7]])

In [5]:
np.compress([False, True], a)

array([3])

cumprod

In [7]:
a  = np.array([1, 2, 3])

In [8]:
np.cumprod(a)

array([1, 2, 6], dtype=int32)

In [10]:
a = np.array([[1, 2, 3],[4, 5, 6]])

In [11]:
np.cumprod(a)

array([  1,   2,   6,  24, 120, 720], dtype=int32)

In [12]:
np.cumprod(a, axis=0)

array([[ 1,  2,  3],
       [ 4, 10, 18]], dtype=int32)

In [13]:
np.cumprod(a, axis=1)

array([[  1,   2,   6],
       [  4,  20, 120]], dtype=int32)

cumsum

In [14]:
np.cumsum(a, axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [15]:
np.cumsum(a, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [16]:
np.cumsum(a, dtype=float)

array([  1.,   3.,   6.,  10.,  15.,  21.])

inner

In [17]:
a = np.array([1, 2, 3])

In [18]:
b = np.array([4, 5, 0])

In [20]:
np.inner(a, b)

14

ndarray.fill

In [23]:
a = np.array([1, 2])

In [26]:
a.fill(0)

In [27]:
a

array([0, 0])

In [28]:
a = np.empty(2)

In [29]:
a.fill(1)

In [30]:
a

array([ 1.,  1.])

imag

In [31]:
a = np.array([1+2j, 2+3j, 3+4j])

In [32]:
a

array([ 1.+2.j,  2.+3.j,  3.+4.j])

In [33]:
a.imag

array([ 2.,  3.,  4.])

In [34]:
np.imag(1 + 1J)

array(1.0)

prod

In [35]:
np.prod([2, 3, 4])

24

In [37]:
np.prod([[2, 3], [4, 5]], axis=1)

array([ 6, 20])

In [38]:
np.prod([[2, 3], [4, 5]], axis=0)

array([ 8, 15])

put

In [39]:
a = np.arange(5)

In [40]:
a

array([0, 1, 2, 3, 4])

In [42]:
np.put(a, [0, 2], [-44, -55])

In [43]:
a

array([-44,   1, -55,   3,   4])

putmask

In [44]:
x = np.arange(6).reshape(2, 3)

In [45]:
np.putmask(x, x>2, x**2)

In [46]:
x

array([[ 0,  1,  2],
       [ 9, 16, 25]])

In [47]:
np.putmask(x, x>1, [-33, -44])

In [48]:
x

array([[  0,   1, -33],
       [-44, -33, -44]])

real

In [49]:
a = np.array([1+1j, 2+2j])

In [50]:
np.real(a)

array([ 1.,  2.])

In [51]:
a.real

array([ 1.,  2.])

sum

In [52]:
np.sum([1, 2])

3

In [54]:
np.sum([[1, 2], [2, 3]], axis=0)

array([3, 5])

In [55]:
np.sum([[1, 2], [2, 3]], axis=1)

array([3, 5])

In [56]:
np.sum([[1, 0], [0, 1]])

2