In [1]:
import numpy as np

argmax

In [4]:
a = np.arange(12).reshape(3, 4)

In [5]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.argmax(a)

11

In [7]:
np.argmax(a, axis=0)

array([2, 2, 2, 2], dtype=int64)

In [8]:
np.argmax(a, axis=1)

array([3, 3, 3], dtype=int64)

argmin

In [9]:
a = np.arange(12).reshape(3, 4)

In [10]:
np.argmin(a)

0

In [11]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
np.argmin(a, axis=0)

array([0, 0, 0, 0], dtype=int64)

In [14]:
np.argmin(a, axis=1)

array([0, 0, 0], dtype=int64)

In [17]:
np.argmin(np.arange(2, 7, 2))

0

argsort

In [18]:
x = np.array([3, 2, 1])

In [19]:
np.argsort(x)

array([2, 1, 0], dtype=int64)

In [20]:
x = np.array([[4,2], [3, 6]])

In [21]:
x

array([[4, 2],
       [3, 6]])

In [23]:
np.argsort(x, axis=0)

array([[1, 0],
       [0, 1]], dtype=int64)

In [24]:
np.argsort(x, axis=1)

array([[1, 0],
       [0, 1]], dtype=int64)

max

In [25]:
max(np.array([4, 5, 6]))

6

min

In [26]:
min(np.array([4, 5, 6]))

4

ptp

In [27]:
x = np.array([[2, 3], [4, 5]])

In [28]:
np.ptp(x, axis=0)

array([2, 2])

In [29]:
np.ptp(x, axis=1)

array([1, 1])

searchsorted

In [30]:
np.searchsorted([1,2, 3, 4], 3)

2

In [32]:
np.searchsorted([10, 12, 14], 13, side='right')

2

In [33]:
np.searchsorted([1, 3, 5, 7], [2,4, 6])

array([1, 2, 3], dtype=int64)

sort

In [37]:
a = np.array([[1, 9], [5, 8]])

In [38]:
np.sort(a)

array([[1, 9],
       [5, 8]])

In [39]:
np.sort(a, axis=None)

array([1, 5, 8, 9])

In [40]:
np.sort(a, axis=0)

array([[1, 8],
       [5, 9]])

In [41]:
dtype=[('name', 'S10'), ('height', float), ('age', int)]

In [42]:
values = [('Rittick', 180.0, 27), ('Harshit', 180.0, 28), ('Shivam', 190, 27)]

In [43]:
a = np.array(values, dtype=dtype)

In [44]:
np.sort(a, order='height')

array([(b'Harshit', 180.0, 28), (b'Rittick', 180.0, 27),
       (b'Shivam', 190.0, 27)], 
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])