In [1]:
import numpy as np

all

In [3]:
np.all([[True, False], [True, False]], axis=0)

array([ True, False], dtype=bool)

In [4]:
np.all([-1, 4, 5])

True

any

In [5]:
np.any([[True, False],[True, False]])

True

In [6]:
np.any([1, 0, 4])

True

nonzero

In [10]:
x = np.array([[0, 2, 3], 
             [4, 0, 6],
             [7, 0, 9]])

In [11]:
np.nonzero(x)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 0, 2, 0, 2], dtype=int64))

In [12]:
x[np.nonzero(x)]

array([2, 3, 4, 6, 7, 9])

In [13]:
x > 2

array([[False, False,  True],
       [ True, False,  True],
       [ True, False,  True]], dtype=bool)

In [14]:
x[x>2]

array([3, 4, 6, 7, 9])

where

In [15]:
x = np.arange(12).reshape(3, 4)

In [16]:
np.where(x >5)

(array([1, 1, 2, 2, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3], dtype=int64))

In [17]:
x[np.where(x<3)]

array([0, 1, 2])